config/routes.rb
Rails.application.routes.draw do
  get 'check/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config

  resources :users
  get 'register/confirm'

  resources :orders
  resources :line_items
  resources :carts

  get 'store/index'

  root 'store#index'
  resources :products do
    get :who_bought, on: :member
  end

  resources :products
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items,dependent: :destroy

  def total_price
    line_items.to_a.sum  {|item| item.total_price}
  end

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price*quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = ["Check","Credit cart","Purchase order"]
  has_many :line_items, dependent: :destroy
  validates :name,:address,:email,presence: true
  validates :pay_type, :inclusion => PAYMENT_TYPES


  def add_line_items_from_cart(cart)
    cart.line_items.each do |item |
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders,through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title,:description,:image_url,presence: true
  validates :image_url, allow_blank: true, format: {
                          with:
                              %r{\.(gif|jpg|png)}i,
                          message: 'must be a URL for GIF, JPG or PNG image.'
                      }
  validates :price,numericality: {greater_than_or_equal_to: 0.01}
  validates :title,uniqueness: true

  private
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base,'LineItems present')
      return false
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  validates :name,presence: true,uniqueness: true
  :has_secure_password
end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
skip_before_filter :authorize

  def show
    begin
    @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart id #{params[:id]}"
      redirect_to store_index_url,notice: 'Invalid Cart'
    else
      respond_to do |format|
        format.html
        format.json {render json: @cart}
      end
    end

  end

  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html {redirect_to store_index_url}
      format.json {head :no_content}
    end
  end

  private

    def cart_params
      params.require(:cart).permit()
    end
end

app/controllers/check_controller.rb
class CheckController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  skip_before_filter :authorize

  def index
    @orders = Order.paginate(page: params[:page],per_page: 10)
    respond_to do |format|
      format.html
      format.json{render json: @orders}
    end
  end


  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to store_index_url, notice: 'Your Cart is empty!'
      return
    end

    @order = Order.new
    respond_to do |format|
      format.html
      format.json{render json: @order}
    end

  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(current_cart)
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderNotifier.received(@order).deliver
        format.html{redirect_to store_index_url,notice: 'Thank you for your order'}
        format.json{render json: @order,status: :created,location: @order}
      else
        @cart = current_cart
        format.html{redirect_to action: 'new'}
        format.json{render json: @order.errors, status: :unprocessable_entity}
      end

    end
  end

  private

    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base


  def index
    @products = Product.all
  end

  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.atom
    end
  end

  private

    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :authorize
  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to store_index_url;
    else
      redirect_to login_url,alert: 'Invalid username or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to store_index_url,notice: 'Logged out'
  end

  def new

  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize
  def index
    if session[:counter].nil?
      session[:counter] = 1
    else
      session[:counter] += 1
    end
    @products = Product.order(:title)
    @cart = current_cart

  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base


  def index
    @users = User.order(:name)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_index_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user,
                             status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors,
                             status: :unprocessable_entity }
      end
    end
  end
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url,notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors,
                             status: :unprocessable_entity }
      end
    end
  end
  private

    def user_params
      params.require(:user).permit(:name, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/check_helper.rb
module CheckHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<%if !@cart.line_items.empty? %>


  <ul class="list-group">
    <% @cart.line_items.each do |item| %>
        <li class="list-group-item"><%= item.quantity %>&times;<%= item.product.title %></li>
    <% end %>
  </ul>


  <ul class="list-group">

    <% if !@cart.line_items.empty? %>
        <li class="list-group-item" style="color: red;">Total <%= number_to_currency (@cart.total_price) %></li>
    <% end%>


  </ul>
<table>
  <tr>
    <th><%= button_to 'Checkout',new_order_path,method: :get,class: 'btn btn-success' %></th>
    <th> <%= button_to 'Empty Cart',@cart,method: :delete,confirm: 'Are you sure?',class: 'btn btn-danger' %></th>
  </tr>
</table>

</div>

<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render 'carts/cart' %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>



<br>



<div class="container">
  <div class="row">

    <% @products.each do |product| %>

        <div class="col-sm-4 col-lg-4 col-md-4">
          <div class="thumbnail">
            <img src="http://placehold.it/320x150" alt="">
            <div class="caption">
              <h4 class="pull-right"><%= number_to_currency product.price %></h4>
              <h4><a href="#"><%=link_to product.title, product %></a>
              </h4>
              <p><%=truncate( product.description, length: 100) %> <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
            </div>
            <a href="#" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-shopping-cart"></span> Bootstrap Button</a>
            <div class="ratings">
              <p class="pull-right">15 reviews</p>
              <p>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
              </p>
            </div>
          </div>
        </div>
    <% end %>


  </div>

</div>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <img src="http://placehold.it/320x150" alt="">
    <div class="caption">
      <h4 class="pull-right"><%= number_to_currency @product.price %></h4>
      <h4><a href="#"><%= @product.title %></a>
      </h4>
      <p><%= @product.description %> <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
    </div>
    <a href="#" class="btn btn-warning btn-sm"><span class="glyphicon glyphicon-shopping-cart"></span> Bootstrap Button</a>
    <div class="ratings">
      <p class="pull-right">15 reviews</p>
      <p>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
      </p>
    </div>
  </div>
  <%= render 'layouts/disqus'%>
</div>
</br>
<hr>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>